
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serve-url: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9196

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kvineet881/cloud-config-server-hystrix